worker_processes 1;

events { worker_connections 1024; }

http {
  sendfile on;

  upstream api_upstream {
    server api:8000;
  }

  upstream attacker_upstream {
    server attacker:8000;
  }

  upstream trusted_upstream {
    server trusted_http:8000;
  }

  server {
    listen 80;
    server_name api.local;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 80;
    server_name attacker.local;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 80;
    server_name trusted.local;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name api.local;

    ssl_certificate /etc/nginx/certs/local.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;

    location / {
      proxy_pass http://api_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }

  server {
    listen 443 ssl;
    server_name attacker.local;

    ssl_certificate /etc/nginx/certs/local.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;

    location / {
      proxy_pass http://attacker_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }

  server {
    listen 443 ssl;
    server_name trusted.local;

    ssl_certificate /etc/nginx/certs/local.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;

    location / {
      proxy_pass http://trusted_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
